#include <assert.h>
#include <stdint.h>

#include <borrowlink/borrowlink.h>

int main(void)
{
    assert(BORROWLINK_PROTOCOL_VERSION == UINT8_C(0x01));
    assert(BORROWLINK_BEACON_SIZE == 6u);
    assert(BORROWLINK_PROFILE_PRESENCE == UINT8_C(0x00));
    assert(BORROWLINK_PROFILE_HTTP == UINT8_C(0x01));
    assert(BORROWLINK_PROFILE_STREAM == UINT8_C(0x02));
    assert(BORROWLINK_PROFILE_MESSAGE == UINT8_C(0x03));
    assert(BORROWLINK_BEACON_FLAG_REALTIME == UINT8_C(0x01));
    assert(BORROWLINK_BEACON_FLAG_ANNOUNCEMENT == UINT8_C(0x02));
    assert(BORROWLINK_BEACON_FLAG_KEEP_CONNECTED == UINT8_C(0x04));
    assert(BORROWLINK_BEACON_FLAG_KNOWN_MASK == UINT8_C(0x07));

    assert(BORROWLINK_FRAME_HEADER_SIZE == 3u);
    assert(BORROWLINK_OPCODE_DATA == UINT8_C(0x00));
    assert(BORROWLINK_OPCODE_DATA_END_MESSAGE == UINT8_C(0x01));
    assert(BORROWLINK_OPCODE_DATA_END_STREAM == UINT8_C(0x02));
    assert(BORROWLINK_OPCODE_DATA_END_MESSAGE_STREAM == UINT8_C(0x03));
    assert(BORROWLINK_OPCODE_HELLO == UINT8_C(0x10));
    assert(BORROWLINK_OPCODE_ACCEPT == UINT8_C(0x11));
    assert(BORROWLINK_OPCODE_STATUS == UINT8_C(0x12));
    assert(BORROWLINK_OPCODE_RESET == UINT8_C(0x13));

    assert(BORROWLINK_DELIVERY_RELIABLE == UINT8_C(0x00));
    assert(BORROWLINK_DELIVERY_REALTIME == UINT8_C(0x01));
    assert(BORROWLINK_HELLO_PAYLOAD_SIZE == 15u);
    assert(BORROWLINK_ACCEPT_PAYLOAD_SIZE == 14u);

    assert(BORROWLINK_RESET_NO_NETWORK == UINT8_C(0x10));
    assert(BORROWLINK_RESET_UPSTREAM_FAILED == UINT8_C(0x11));
    assert(BORROWLINK_RESET_UPSTREAM_TIMEOUT == UINT8_C(0x12));
    assert(BORROWLINK_RESET_REJECTED == UINT8_C(0x13));
    assert(BORROWLINK_RESET_UNSUPPORTED_PROFILE == UINT8_C(0x14));
    assert(BORROWLINK_RESET_PROTOCOL_ERROR == UINT8_C(0x15));
    assert(BORROWLINK_RESET_BUSY == UINT8_C(0x16));
    assert(BORROWLINK_RESET_SECURITY_ERROR == UINT8_C(0x17));
    assert(BORROWLINK_RESET_LIMIT_EXCEEDED == UINT8_C(0x18));
    assert(BORROWLINK_RESET_UNSUPPORTED_OPCODE == UINT8_C(0x19));

    assert(BL_OK == 0);
    assert(BL_ERROR_ARGUMENT != BL_OK);
    return 0;
}
