#pragma once

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define BORROWLINK_PROTOCOL_VERSION UINT8_C(0x01)
#define BORROWLINK_BEACON_SIZE 6u

#define BORROWLINK_PROFILE_PRESENCE UINT8_C(0x00)
#define BORROWLINK_PROFILE_HTTP UINT8_C(0x01)
#define BORROWLINK_PROFILE_STREAM UINT8_C(0x02)
#define BORROWLINK_PROFILE_MESSAGE UINT8_C(0x03)

#define BORROWLINK_BEACON_FLAG_REALTIME UINT8_C(0x01)
#define BORROWLINK_BEACON_FLAG_ANNOUNCEMENT UINT8_C(0x02)
#define BORROWLINK_BEACON_FLAG_KEEP_CONNECTED UINT8_C(0x04)
#define BORROWLINK_BEACON_FLAG_KNOWN_MASK UINT8_C(0x07)

#define BORROWLINK_FRAME_HEADER_SIZE 3u
#define BORROWLINK_OPCODE_DATA UINT8_C(0x00)
#define BORROWLINK_OPCODE_DATA_END_MESSAGE UINT8_C(0x01)
#define BORROWLINK_OPCODE_DATA_END_STREAM UINT8_C(0x02)
#define BORROWLINK_OPCODE_DATA_END_MESSAGE_STREAM UINT8_C(0x03)
#define BORROWLINK_OPCODE_HELLO UINT8_C(0x10)
#define BORROWLINK_OPCODE_ACCEPT UINT8_C(0x11)
#define BORROWLINK_OPCODE_STATUS UINT8_C(0x12)
#define BORROWLINK_OPCODE_RESET UINT8_C(0x13)

#define BORROWLINK_DELIVERY_RELIABLE UINT8_C(0x00)
#define BORROWLINK_DELIVERY_REALTIME UINT8_C(0x01)
#define BORROWLINK_HELLO_PAYLOAD_SIZE 15u
#define BORROWLINK_ACCEPT_PAYLOAD_SIZE 14u

#define BORROWLINK_RESET_NO_NETWORK UINT8_C(0x10)
#define BORROWLINK_RESET_UPSTREAM_FAILED UINT8_C(0x11)
#define BORROWLINK_RESET_UPSTREAM_TIMEOUT UINT8_C(0x12)
#define BORROWLINK_RESET_REJECTED UINT8_C(0x13)
#define BORROWLINK_RESET_UNSUPPORTED_PROFILE UINT8_C(0x14)
#define BORROWLINK_RESET_PROTOCOL_ERROR UINT8_C(0x15)
#define BORROWLINK_RESET_BUSY UINT8_C(0x16)
#define BORROWLINK_RESET_SECURITY_ERROR UINT8_C(0x17)
#define BORROWLINK_RESET_LIMIT_EXCEEDED UINT8_C(0x18)
#define BORROWLINK_RESET_UNSUPPORTED_OPCODE UINT8_C(0x19)

typedef enum {
    BL_OK = 0,
    BL_ERROR_ARGUMENT,
    BL_ERROR_BUFFER_TOO_SMALL,
    BL_ERROR_MALFORMED,
    BL_ERROR_UNSUPPORTED_VERSION,
    BL_ERROR_UNSUPPORTED_PROFILE,
    BL_ERROR_UNSUPPORTED_DELIVERY,
    BL_ERROR_UNSUPPORTED_OPCODE
} bl_result;

typedef struct {
    uint8_t version;
    uint8_t profile;
    uint16_t xid;
    uint8_t attempt;
    uint8_t flags;
} bl_beacon;

bl_result bl_beacon_encode(uint8_t *output,
                           size_t output_size,
                           const bl_beacon *beacon);
bl_result bl_beacon_decode(bl_beacon *beacon,
                           const uint8_t *input,
                           size_t input_size);

#ifdef __cplusplus
}
#endif
