#pragma once

#include <stdint.h>

#define BORROWLINK_PROTOCOL_VERSION UINT8_C(0x01)
#define BORROWLINK_INTENT_HTTP_REQUEST UINT8_C(0x01)

#define BORROWLINK_DISCOVERY_PAYLOAD_SIZE 6u
#define BORROWLINK_CHUNK_HEADER_SIZE 3u
#define BORROWLINK_CHUNK_FLAG_FINAL UINT8_C(0x01)

#define BORROWLINK_CONTROL_IN_PROGRESS UINT8_C(0x00)
#define BORROWLINK_CONTROL_COMPLETE UINT8_C(0x01)
#define BORROWLINK_CONTROL_NO_NETWORK UINT8_C(0x10)
#define BORROWLINK_CONTROL_UPSTREAM_ERROR UINT8_C(0x11)
#define BORROWLINK_CONTROL_UPSTREAM_TIMEOUT UINT8_C(0x12)
#define BORROWLINK_CONTROL_REJECTED UINT8_C(0x13)
